### ISSUE TITLE
有个bug, indicaterStyle设置无效

### ISSUE THREAD

**Issue by nanatot** [netyouli/react-native-whc-banner#2]
在Banner中遗漏了{...this.props},
故在BannerIndicater中无法获取到indicaterStyle,
希尽快修复一下,谢谢。
`<BannerIndicater
                    ref = {(ref) => {this.indicater = ref}}
                    style = {indicaterStyle}
                    indicaterType = {indicaterType}
                    indicaterAlign = {indicaterAlign}
                    dotStyle = {dotStyle}
                    currentDotStyle = {currentDotStyle}
                    circleStyle = {circleStyle}
                    numberStyle = {numberStyle}
                    titleStyle = {titleStyle}
                    count = {length}
                    titles = {titles}
                    {...this.props}
                />`

**Comment by netyouli** [comment]
没有问题的indicaterStyle 就是设置BannerIndicater样式的

**Comment by netyouli** [comment]
indicaterStyle无效已经修复了谢谢，不是你说这个问题
